### PR TITLE
SOC-291 show agent UID when hovering over name in people list

### PR DESCRIPTION
**Pull request by VilleImmonen**
My previous pull request went into the master branch. Changed.

### CODE REVIEW

**Comment by ikamthania** [comment]
Thanks for pr Ville. Will check and try to merge it

**Comment by ikamthania** [comment]
Hi @VilleImmonen . Is this SOC complete. I see some comments from @edeykholt questioning "one can create a connection to themselves" and "how should these be disambiguated when seeing Names on the Connections List". Not sure if it answers all of these. Also we are currently integrating a new ui for connection results so we might not be able to merge it right now.

**Comment by ikamthania** [comment]
However since this is not a breaking change we will merge it once the new ui is checked in. Thanks again for the pr.

**Comment by VilleImmonen** [comment]
Hi @ikamthania . This does not complete the SOC. Since the connection does not have any additional info right now about the target, there is very little distinguishable information to be shown. The tooltip can be expanded once this information is available. Also this does not add anything to "To (of a New post modal), From/To (on an individual post)", but the tooltip can be easily used in this context also.

**Pull request merged**
